language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.10.6
install: bundle install --path vendor/bundle --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
script: bundle exec rake test
